server:
  port: 9085
spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: 192.168.22.140:9093,192.168.22.141:9093,192.168.22.142:9093
    consumer:
      auto-commit-interval: 1000
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 20
      properties:
        request:
          timeout:
            ms: 180000
        session:
          timeout:
            ms: 120000
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      concurrency: 2
      missing-topics-fatal: false
    producer:
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 0
      retries: 0
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  config: classpath:log/logback-spring.xml
