package com.zw.cloud.mybatis.plus.utils;

import com.alibaba.fastjson2.JSON;
import com.zw.cloud.mybatis.plus.entity.report.ReportProductCount;

import java.util.List;

public class MockEntityUtils {

    public static List<ReportProductCount> mockReportProductCountList() {
        String s = "[\n" +
                "    {\n" +
                "        \"blackProductNum\":3,\n" +
                "        \"blackProductQuantity\":60,\n" +
                "        \"blackProductQuantityRate\":60,\n" +
                "        \"calcDay\":\"2023-06-22\",\n" +
                "        \"craftProductInfo\":{\n" +
                "            \"1\":{\n" +
                "                \"productNum\":\"6\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"60\",\n" +
                "                \"whiteProductNum\":\"4\",\n" +
                "                \"productQuantityRate\":\"60\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"40\",\n" +
                "                \"blackProductQuantityRate\":\"33\",\n" +
                "                \"whiteProductQuantityRate\":\"66\"\n" +
                "            },\n" +
                "            \"2\":{\n" +
                "                \"productNum\":\"4\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"40\",\n" +
                "                \"whiteProductNum\":\"2\",\n" +
                "                \"productQuantityRate\":\"40\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"20\",\n" +
                "                \"blackProductQuantityRate\":\"50\",\n" +
                "                \"whiteProductQuantityRate\":\"50\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"createTime\":\"2023-06-26 11:14:21\",\n" +
                "        \"createUser\":\"\",\n" +
                "        \"deviceId\":1,\n" +
                "        \"deviceName\":\"1\",\n" +
                "        \"id\":6,\n" +
                "        \"orgCode\":\"devController\",\n" +
                "        \"productNum\":5,\n" +
                "        \"productQuantity\":100,\n" +
                "        \"updateTime\":\"2023-06-26 11:15:03\",\n" +
                "        \"updateUser\":\"\",\n" +
                "        \"whiteProductNum\":2,\n" +
                "        \"whiteProductQuantity\":40,\n" +
                "        \"whiteProductQuantityRate\":40,\n" +
                "        \"workshopId\":1\n" +
                "    },\n" +
                "    {\n" +
                "        \"blackProductNum\":3,\n" +
                "        \"blackProductQuantity\":60,\n" +
                "        \"blackProductQuantityRate\":60,\n" +
                "        \"calcDay\":\"2023-06-23\",\n" +
                "        \"craftProductInfo\":{\n" +
                "            \"1\":{\n" +
                "                \"productNum\":\"4\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"40\",\n" +
                "                \"whiteProductNum\":\"2\",\n" +
                "                \"productQuantityRate\":\"40\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"20\",\n" +
                "                \"blackProductQuantityRate\":\"50\",\n" +
                "                \"whiteProductQuantityRate\":\"50\"\n" +
                "            },\n" +
                "            \"2\":{\n" +
                "                \"productNum\":\"6\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"60\",\n" +
                "                \"whiteProductNum\":\"4\",\n" +
                "                \"productQuantityRate\":\"60\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"40\",\n" +
                "                \"blackProductQuantityRate\":\"33\",\n" +
                "                \"whiteProductQuantityRate\":\"66\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"createTime\":\"2023-06-26 11:14:13\",\n" +
                "        \"createUser\":\"\",\n" +
                "        \"deviceId\":1,\n" +
                "        \"deviceName\":\"1\",\n" +
                "        \"id\":5,\n" +
                "        \"orgCode\":\"devController\",\n" +
                "        \"productNum\":5,\n" +
                "        \"productQuantity\":100,\n" +
                "        \"updateTime\":\"2023-06-26 11:14:13\",\n" +
                "        \"updateUser\":\"\",\n" +
                "        \"whiteProductNum\":2,\n" +
                "        \"whiteProductQuantity\":40,\n" +
                "        \"whiteProductQuantityRate\":40,\n" +
                "        \"workshopId\":1\n" +
                "    },\n" +
                "    {\n" +
                "        \"blackProductNum\":3,\n" +
                "        \"blackProductQuantity\":60,\n" +
                "        \"blackProductQuantityRate\":60,\n" +
                "        \"calcDay\":\"2023-06-24\",\n" +
                "        \"craftProductInfo\":{\n" +
                "            \"1\":{\n" +
                "                \"productNum\":\"4\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"40\",\n" +
                "                \"whiteProductNum\":\"2\",\n" +
                "                \"productQuantityRate\":\"40\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"20\",\n" +
                "                \"blackProductQuantityRate\":\"50\",\n" +
                "                \"whiteProductQuantityRate\":\"50\"\n" +
                "            },\n" +
                "            \"2\":{\n" +
                "                \"productNum\":\"6\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"60\",\n" +
                "                \"whiteProductNum\":\"4\",\n" +
                "                \"productQuantityRate\":\"60\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"40\",\n" +
                "                \"blackProductQuantityRate\":\"33\",\n" +
                "                \"whiteProductQuantityRate\":\"66\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"createTime\":\"2023-06-26 11:14:04\",\n" +
                "        \"createUser\":\"\",\n" +
                "        \"deviceId\":1,\n" +
                "        \"deviceName\":\"1\",\n" +
                "        \"id\":4,\n" +
                "        \"orgCode\":\"devController\",\n" +
                "        \"productNum\":5,\n" +
                "        \"productQuantity\":100,\n" +
                "        \"updateTime\":\"2023-06-26 11:14:04\",\n" +
                "        \"updateUser\":\"\",\n" +
                "        \"whiteProductNum\":2,\n" +
                "        \"whiteProductQuantity\":40,\n" +
                "        \"whiteProductQuantityRate\":40,\n" +
                "        \"workshopId\":1\n" +
                "    },\n" +
                "    {\n" +
                "        \"blackProductNum\":3,\n" +
                "        \"blackProductQuantity\":60,\n" +
                "        \"blackProductQuantityRate\":60,\n" +
                "        \"calcDay\":\"2023-06-25\",\n" +
                "        \"craftProductInfo\":{\n" +
                "            \"1\":{\n" +
                "                \"productNum\":\"4\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"40\",\n" +
                "                \"whiteProductNum\":\"2\",\n" +
                "                \"productQuantityRate\":\"40\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"20\",\n" +
                "                \"blackProductQuantityRate\":\"50\",\n" +
                "                \"whiteProductQuantityRate\":\"50\"\n" +
                "            },\n" +
                "            \"2\":{\n" +
                "                \"productNum\":\"6\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"60\",\n" +
                "                \"whiteProductNum\":\"4\",\n" +
                "                \"productQuantityRate\":\"60\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"40\",\n" +
                "                \"blackProductQuantityRate\":\"33\",\n" +
                "                \"whiteProductQuantityRate\":\"66\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"createTime\":\"2023-06-26 11:13:56\",\n" +
                "        \"createUser\":\"\",\n" +
                "        \"deviceId\":1,\n" +
                "        \"deviceName\":\"1\",\n" +
                "        \"id\":3,\n" +
                "        \"orgCode\":\"devController\",\n" +
                "        \"productNum\":5,\n" +
                "        \"productQuantity\":100,\n" +
                "        \"updateTime\":\"2023-06-26 11:13:56\",\n" +
                "        \"updateUser\":\"\",\n" +
                "        \"whiteProductNum\":2,\n" +
                "        \"whiteProductQuantity\":40,\n" +
                "        \"whiteProductQuantityRate\":40,\n" +
                "        \"workshopId\":1\n" +
                "    },\n" +
                "    {\n" +
                "        \"blackProductNum\":3,\n" +
                "        \"blackProductQuantity\":60,\n" +
                "        \"blackProductQuantityRate\":60,\n" +
                "        \"calcDay\":\"2023-06-26\",\n" +
                "        \"craftProductInfo\":{\n" +
                "            \"1\":{\n" +
                "                \"productNum\":\"4\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"40\",\n" +
                "                \"whiteProductNum\":\"2\",\n" +
                "                \"productQuantityRate\":\"40\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"20\",\n" +
                "                \"blackProductQuantityRate\":\"50\",\n" +
                "                \"whiteProductQuantityRate\":\"50\"\n" +
                "            },\n" +
                "            \"2\":{\n" +
                "                \"productNum\":\"6\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"60\",\n" +
                "                \"whiteProductNum\":\"4\",\n" +
                "                \"productQuantityRate\":\"60\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"40\",\n" +
                "                \"blackProductQuantityRate\":\"33\",\n" +
                "                \"whiteProductQuantityRate\":\"66\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"createTime\":\"2023-06-26 11:13:45\",\n" +
                "        \"createUser\":\"\",\n" +
                "        \"deviceId\":1,\n" +
                "        \"deviceName\":\"1\",\n" +
                "        \"id\":1,\n" +
                "        \"orgCode\":\"devController\",\n" +
                "        \"productNum\":5,\n" +
                "        \"productQuantity\":100,\n" +
                "        \"updateTime\":\"2023-06-26 11:13:45\",\n" +
                "        \"updateUser\":\"\",\n" +
                "        \"whiteProductNum\":2,\n" +
                "        \"whiteProductQuantity\":40,\n" +
                "        \"whiteProductQuantityRate\":40,\n" +
                "        \"workshopId\":1\n" +
                "    },\n" +
                "    {\n" +
                "        \"blackProductNum\":3,\n" +
                "        \"blackProductQuantity\":60,\n" +
                "        \"blackProductQuantityRate\":60,\n" +
                "        \"calcDay\":\"2023-06-26\",\n" +
                "        \"craftProductInfo\":{\n" +
                "            \"1\":{\n" +
                "                \"productNum\":\"4\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"40\",\n" +
                "                \"whiteProductNum\":\"2\",\n" +
                "                \"productQuantityRate\":\"40\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"20\",\n" +
                "                \"blackProductQuantityRate\":\"50\",\n" +
                "                \"whiteProductQuantityRate\":\"50\"\n" +
                "            },\n" +
                "            \"2\":{\n" +
                "                \"productNum\":\"6\",\n" +
                "                \"blackProductNum\":\"2\",\n" +
                "                \"productQuantity\":\"60\",\n" +
                "                \"whiteProductNum\":\"4\",\n" +
                "                \"productQuantityRate\":\"60\",\n" +
                "                \"blackProductQuantity\":\"20\",\n" +
                "                \"whiteProductQuantity\":\"40\",\n" +
                "                \"blackProductQuantityRate\":\"33\",\n" +
                "                \"whiteProductQuantityRate\":\"66\"\n" +
                "            }\n" +
                "        },\n" +
                "        \"createTime\":\"2023-06-26 11:11:31\",\n" +
                "        \"createUser\":\"\",\n" +
                "        \"deviceId\":2,\n" +
                "        \"deviceName\":\"2\",\n" +
                "        \"id\":2,\n" +
                "        \"orgCode\":\"devController\",\n" +
                "        \"productNum\":5,\n" +
                "        \"productQuantity\":100,\n" +
                "        \"updateTime\":\"2023-06-26 11:11:31\",\n" +
                "        \"updateUser\":\"\",\n" +
                "        \"whiteProductNum\":2,\n" +
                "        \"whiteProductQuantity\":40,\n" +
                "        \"whiteProductQuantityRate\":40,\n" +
                "        \"workshopId\":1\n" +
                "    }\n" +
                "]";
        return JSON.parseArray(s,ReportProductCount.class);
    }
}
