server:
  port: 9095
spring:
  application:
    name: rocketmq
  jackson:
    serialization:
      write-dates-as-timestamps: true

rocketmq:
  consumer:
    group: group2
#    pull-batch-size: 2
  name-server: 127.0.0.1:9876
  producer:
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    group: group1
    #消息最大长度 默认1024 * 1024 * 4(4M)
    max-message-size: 4096
    #发送消息失败重试次数，默认2
    retry-times-when-send-failed: 2
    #发送消息超时时间,默认3000
    send-message-timeout: 3000

logging:
  config: classpath:log/logback-spring.xml
  file:
    path: D:/logs/cloud
  level:
    root: info
