spring:
  application:
    name: mybatis-plus-demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
  sql:
    init:
      enabled: false
      #创建表的MySql语句位置
      schema-locations: classpath:schema.sql
      #插入数据的MySql语句的位置
      data-locations: classpath:data.sql


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 50
      max-wait: 10000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: "select 1"
      filters: stat,slf4j
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: password

mybatis-plus:
  #mapper-locations: classpath*:mapper/**/*.xml
  type-handlers-package: com.zw.cloud.mybatis.plus.db.typehandlers.ext
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-underline: true
      id-type: auto
      #logic-delete-field: deleted
      #logic-delete-value: 1
      #logic-not-delete-value: 0

mybatis:

  table:
    auto: create
    #create	    系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    #update	    系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
    #none 		系统不做任何处理。
    #add		新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除 (只在版本1.0.9.RELEASE及以上支持)。
  model:
    pack: com.zw.cloud.mybatis.plus.entity #扫描用于创建表的对象的包名，多个包用“,”隔开
  database:
    type: mysql #数据库类型 目前只支持mysql
