package com.zw.cloud.influxdb.service.utils;

import com.alibaba.fastjson.JSON;
import com.zw.cloud.influxdb.entity.IotInfoDo;

import java.util.List;

public class MockEntityUtils {

    public static List<IotInfoDo> buildIotInfoDoList() {
        String s = "[\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:27:00Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":22,\n" +
                "        \"troughActualTemp1\":22,\n" +
                "        \"troughPresetTemp2\":22,\n" +
                "        \"troughActualTemp2\":22,\n" +
                "        \"troughPresetTemp3\":22,\n" +
                "        \"troughActualTemp3\":22,\n" +
                "        \"troughPresetTemp4\":22,\n" +
                "        \"troughActualTemp4\":22,\n" +
                "        \"troughPresetTemp5\":22,\n" +
                "        \"troughActualTemp5\":22,\n" +
                "        \"troughPresetTemp6\":22,\n" +
                "        \"troughActualTemp6\":22,\n" +
                "        \"troughPresetTemp7\":22,\n" +
                "        \"troughActualTemp7\":22,\n" +
                "        \"troughPresetTemp8\":22,\n" +
                "        \"troughActualTemp8\":22,\n" +
                "        \"troughPresetTemp9\":22,\n" +
                "        \"troughActualTemp9\":22,\n" +
                "        \"troughPresetTemp10\":22,\n" +
                "        \"troughActualTemp10\":22,\n" +
                "        \"troughPresetTemp11\":22,\n" +
                "        \"troughActualTemp11\":22,\n" +
                "        \"troughPresetTemp12\":22,\n" +
                "        \"troughActualTemp12\":22,\n" +
                "        \"troughPresetTemp13\":22,\n" +
                "        \"troughActualTemp13\":22,\n" +
                "        \"troughPresetTemp14\":22,\n" +
                "        \"troughActualTemp14\":22,\n" +
                "        \"troughPresetTemp15\":22,\n" +
                "        \"troughActualTemp15\":22,\n" +
                "        \"troughPresetTemp16\":22,\n" +
                "        \"troughActualTemp16\":22,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:32:23Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":33,\n" +
                "        \"troughActualTemp1\":33,\n" +
                "        \"troughPresetTemp2\":33,\n" +
                "        \"troughActualTemp2\":33,\n" +
                "        \"troughPresetTemp3\":33,\n" +
                "        \"troughActualTemp3\":33,\n" +
                "        \"troughPresetTemp4\":33,\n" +
                "        \"troughActualTemp4\":33,\n" +
                "        \"troughPresetTemp5\":33,\n" +
                "        \"troughActualTemp5\":33,\n" +
                "        \"troughPresetTemp6\":33,\n" +
                "        \"troughActualTemp6\":33,\n" +
                "        \"troughPresetTemp7\":33,\n" +
                "        \"troughActualTemp7\":33,\n" +
                "        \"troughPresetTemp8\":33,\n" +
                "        \"troughActualTemp8\":33,\n" +
                "        \"troughPresetTemp9\":33,\n" +
                "        \"troughActualTemp9\":33,\n" +
                "        \"troughPresetTemp10\":33,\n" +
                "        \"troughActualTemp10\":33,\n" +
                "        \"troughPresetTemp11\":33,\n" +
                "        \"troughActualTemp11\":33,\n" +
                "        \"troughPresetTemp12\":33,\n" +
                "        \"troughActualTemp12\":33,\n" +
                "        \"troughPresetTemp13\":33,\n" +
                "        \"troughActualTemp13\":33,\n" +
                "        \"troughPresetTemp14\":33,\n" +
                "        \"troughActualTemp14\":33,\n" +
                "        \"troughPresetTemp15\":33,\n" +
                "        \"troughActualTemp15\":33,\n" +
                "        \"troughPresetTemp16\":33,\n" +
                "        \"troughActualTemp16\":33,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:32:30Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":33,\n" +
                "        \"troughActualTemp1\":33,\n" +
                "        \"troughPresetTemp2\":33,\n" +
                "        \"troughActualTemp2\":33,\n" +
                "        \"troughPresetTemp3\":33,\n" +
                "        \"troughActualTemp3\":33,\n" +
                "        \"troughPresetTemp4\":33,\n" +
                "        \"troughActualTemp4\":33,\n" +
                "        \"troughPresetTemp5\":33,\n" +
                "        \"troughActualTemp5\":33,\n" +
                "        \"troughPresetTemp6\":33,\n" +
                "        \"troughActualTemp6\":33,\n" +
                "        \"troughPresetTemp7\":33,\n" +
                "        \"troughActualTemp7\":33,\n" +
                "        \"troughPresetTemp8\":33,\n" +
                "        \"troughActualTemp8\":33,\n" +
                "        \"troughPresetTemp9\":33,\n" +
                "        \"troughActualTemp9\":33,\n" +
                "        \"troughPresetTemp10\":33,\n" +
                "        \"troughActualTemp10\":33,\n" +
                "        \"troughPresetTemp11\":33,\n" +
                "        \"troughActualTemp11\":33,\n" +
                "        \"troughPresetTemp12\":33,\n" +
                "        \"troughActualTemp12\":33,\n" +
                "        \"troughPresetTemp13\":33,\n" +
                "        \"troughActualTemp13\":33,\n" +
                "        \"troughPresetTemp14\":33,\n" +
                "        \"troughActualTemp14\":33,\n" +
                "        \"troughPresetTemp15\":33,\n" +
                "        \"troughActualTemp15\":33,\n" +
                "        \"troughPresetTemp16\":33,\n" +
                "        \"troughActualTemp16\":33,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:32:35Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":44,\n" +
                "        \"troughActualTemp1\":44,\n" +
                "        \"troughPresetTemp2\":44,\n" +
                "        \"troughActualTemp2\":44,\n" +
                "        \"troughPresetTemp3\":44,\n" +
                "        \"troughActualTemp3\":44,\n" +
                "        \"troughPresetTemp4\":44,\n" +
                "        \"troughActualTemp4\":44,\n" +
                "        \"troughPresetTemp5\":44,\n" +
                "        \"troughActualTemp5\":44,\n" +
                "        \"troughPresetTemp6\":44,\n" +
                "        \"troughActualTemp6\":44,\n" +
                "        \"troughPresetTemp7\":44,\n" +
                "        \"troughActualTemp7\":44,\n" +
                "        \"troughPresetTemp8\":44,\n" +
                "        \"troughActualTemp8\":44,\n" +
                "        \"troughPresetTemp9\":44,\n" +
                "        \"troughActualTemp9\":44,\n" +
                "        \"troughPresetTemp10\":44,\n" +
                "        \"troughActualTemp10\":44,\n" +
                "        \"troughPresetTemp11\":44,\n" +
                "        \"troughActualTemp11\":44,\n" +
                "        \"troughPresetTemp12\":44,\n" +
                "        \"troughActualTemp12\":44,\n" +
                "        \"troughPresetTemp13\":44,\n" +
                "        \"troughActualTemp13\":44,\n" +
                "        \"troughPresetTemp14\":44,\n" +
                "        \"troughActualTemp14\":44,\n" +
                "        \"troughPresetTemp15\":44,\n" +
                "        \"troughActualTemp15\":44,\n" +
                "        \"troughPresetTemp16\":44,\n" +
                "        \"troughActualTemp16\":44,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:32:44Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":44,\n" +
                "        \"troughActualTemp1\":44,\n" +
                "        \"troughPresetTemp2\":44,\n" +
                "        \"troughActualTemp2\":44,\n" +
                "        \"troughPresetTemp3\":44,\n" +
                "        \"troughActualTemp3\":44,\n" +
                "        \"troughPresetTemp4\":44,\n" +
                "        \"troughActualTemp4\":44,\n" +
                "        \"troughPresetTemp5\":44,\n" +
                "        \"troughActualTemp5\":44,\n" +
                "        \"troughPresetTemp6\":44,\n" +
                "        \"troughActualTemp6\":44,\n" +
                "        \"troughPresetTemp7\":44,\n" +
                "        \"troughActualTemp7\":44,\n" +
                "        \"troughPresetTemp8\":44,\n" +
                "        \"troughActualTemp8\":44,\n" +
                "        \"troughPresetTemp9\":44,\n" +
                "        \"troughActualTemp9\":44,\n" +
                "        \"troughPresetTemp10\":44,\n" +
                "        \"troughActualTemp10\":44,\n" +
                "        \"troughPresetTemp11\":44,\n" +
                "        \"troughActualTemp11\":44,\n" +
                "        \"troughPresetTemp12\":44,\n" +
                "        \"troughActualTemp12\":44,\n" +
                "        \"troughPresetTemp13\":44,\n" +
                "        \"troughActualTemp13\":44,\n" +
                "        \"troughPresetTemp14\":44,\n" +
                "        \"troughActualTemp14\":44,\n" +
                "        \"troughPresetTemp15\":44,\n" +
                "        \"troughActualTemp15\":44,\n" +
                "        \"troughPresetTemp16\":44,\n" +
                "        \"troughActualTemp16\":44,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:32:47Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":55,\n" +
                "        \"troughActualTemp1\":55,\n" +
                "        \"troughPresetTemp2\":55,\n" +
                "        \"troughActualTemp2\":55,\n" +
                "        \"troughPresetTemp3\":55,\n" +
                "        \"troughActualTemp3\":55,\n" +
                "        \"troughPresetTemp4\":55,\n" +
                "        \"troughActualTemp4\":55,\n" +
                "        \"troughPresetTemp5\":55,\n" +
                "        \"troughActualTemp5\":55,\n" +
                "        \"troughPresetTemp6\":55,\n" +
                "        \"troughActualTemp6\":55,\n" +
                "        \"troughPresetTemp7\":55,\n" +
                "        \"troughActualTemp7\":55,\n" +
                "        \"troughPresetTemp8\":55,\n" +
                "        \"troughActualTemp8\":55,\n" +
                "        \"troughPresetTemp9\":55,\n" +
                "        \"troughActualTemp9\":55,\n" +
                "        \"troughPresetTemp10\":55,\n" +
                "        \"troughActualTemp10\":55,\n" +
                "        \"troughPresetTemp11\":55,\n" +
                "        \"troughActualTemp11\":55,\n" +
                "        \"troughPresetTemp12\":55,\n" +
                "        \"troughActualTemp12\":55,\n" +
                "        \"troughPresetTemp13\":55,\n" +
                "        \"troughActualTemp13\":55,\n" +
                "        \"troughPresetTemp14\":55,\n" +
                "        \"troughActualTemp14\":55,\n" +
                "        \"troughPresetTemp15\":55,\n" +
                "        \"troughActualTemp15\":55,\n" +
                "        \"troughPresetTemp16\":55,\n" +
                "        \"troughActualTemp16\":55,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    },\n" +
                "    {\n" +
                "        \"time\":\"2023-08-18T03:32:50Z\",\n" +
                "        \"rtime\":0,\n" +
                "        \"ctime\":0,\n" +
                "        \"messageType\":0,\n" +
                "        \"eventCode\":0,\n" +
                "        \"speedSetting\":0,\n" +
                "        \"speed\":0,\n" +
                "        \"output\":0,\n" +
                "        \"troughPresetTemp1\":22,\n" +
                "        \"troughActualTemp1\":22,\n" +
                "        \"troughPresetTemp2\":22,\n" +
                "        \"troughActualTemp2\":22,\n" +
                "        \"troughPresetTemp3\":22,\n" +
                "        \"troughActualTemp3\":22,\n" +
                "        \"troughPresetTemp4\":22,\n" +
                "        \"troughActualTemp4\":22,\n" +
                "        \"troughPresetTemp5\":22,\n" +
                "        \"troughActualTemp5\":22,\n" +
                "        \"troughPresetTemp6\":22,\n" +
                "        \"troughActualTemp6\":22,\n" +
                "        \"troughPresetTemp7\":22,\n" +
                "        \"troughActualTemp7\":22,\n" +
                "        \"troughPresetTemp8\":22,\n" +
                "        \"troughActualTemp8\":22,\n" +
                "        \"troughPresetTemp9\":22,\n" +
                "        \"troughActualTemp9\":22,\n" +
                "        \"troughPresetTemp10\":22,\n" +
                "        \"troughActualTemp10\":22,\n" +
                "        \"troughPresetTemp11\":22,\n" +
                "        \"troughActualTemp11\":22,\n" +
                "        \"troughPresetTemp12\":22,\n" +
                "        \"troughActualTemp12\":22,\n" +
                "        \"troughPresetTemp13\":22,\n" +
                "        \"troughActualTemp13\":22,\n" +
                "        \"troughPresetTemp14\":22,\n" +
                "        \"troughActualTemp14\":22,\n" +
                "        \"troughPresetTemp15\":22,\n" +
                "        \"troughActualTemp15\":22,\n" +
                "        \"troughPresetTemp16\":22,\n" +
                "        \"troughActualTemp16\":22,\n" +
                "        \"steamerPresetTemp\":0,\n" +
                "        \"steamerActualTemp\":0,\n" +
                "        \"feedCenteringTensionPreset\":0,\n" +
                "        \"feedCenteringTensionActual\":0,\n" +
                "        \"tension1\":33,\n" +
                "        \"tensionAct1\":33,\n" +
                "        \"tension2\":33,\n" +
                "        \"tensionAct2\":33,\n" +
                "        \"tension3\":33,\n" +
                "        \"tensionAct3\":33,\n" +
                "        \"tension4\":33,\n" +
                "        \"tensionAct4\":33,\n" +
                "        \"tension5\":33,\n" +
                "        \"tensionAct5\":33,\n" +
                "        \"tension6\":33,\n" +
                "        \"tensionAct6\":33,\n" +
                "        \"tension7\":33,\n" +
                "        \"tensionAct7\":33,\n" +
                "        \"tension8\":33,\n" +
                "        \"tensionAct8\":33,\n" +
                "        \"tension9\":33,\n" +
                "        \"tensionAct9\":33,\n" +
                "        \"tension10\":33,\n" +
                "        \"tensionAct10\":33,\n" +
                "        \"tension11\":33,\n" +
                "        \"tensionAct11\":33,\n" +
                "        \"tension12\":33,\n" +
                "        \"tensionAct12\":33,\n" +
                "        \"tension13\":33,\n" +
                "        \"tensionAct13\":33,\n" +
                "        \"tension14\":33,\n" +
                "        \"tensionAct14\":33,\n" +
                "        \"tension15\":33,\n" +
                "        \"tensionAct15\":33,\n" +
                "        \"tension16\":33,\n" +
                "        \"tensionAct16\":33,\n" +
                "        \"tensionOutlePositionPreset\":0,\n" +
                "        \"tensionOutlePositionActual\":0,\n" +
                "        \"inflowRate1\":44,\n" +
                "        \"inflowRateAct1\":44,\n" +
                "        \"inflowRate2\":44,\n" +
                "        \"inflowRateAct2\":44,\n" +
                "        \"inflowRate3\":44,\n" +
                "        \"inflowRateAct3\":44,\n" +
                "        \"inflowRate4\":44,\n" +
                "        \"inflowRateAct4\":44,\n" +
                "        \"waterUptake1\":55,\n" +
                "        \"waterUptakeAct1\":55,\n" +
                "        \"waterUptake2\":55,\n" +
                "        \"waterUptakeAct2\":55,\n" +
                "        \"waterUptake3\":55,\n" +
                "        \"waterUptakeAct3\":55,\n" +
                "        \"waterUptake4\":55,\n" +
                "        \"waterUptakeAct4\":55,\n" +
                "        \"assistantPreset1\":66,\n" +
                "        \"assistantAct1\":66,\n" +
                "        \"assistantPreset2\":66,\n" +
                "        \"assistantAct2\":66,\n" +
                "        \"assistantPreset3\":66,\n" +
                "        \"assistantAct3\":66,\n" +
                "        \"assistantPreset4\":66,\n" +
                "        \"assistantAct4\":66,\n" +
                "        \"batchConsumption1\":0,\n" +
                "        \"batchConsumption2\":0,\n" +
                "        \"batchConsumption3\":0,\n" +
                "        \"batchConsumption4\":0,\n" +
                "        \"totalConsumption1\":0,\n" +
                "        \"totalConsumption2\":0,\n" +
                "        \"totalConsumption3\":0,\n" +
                "        \"totalConsumption4\":0,\n" +
                "        \"feedRollingPressure\":0,\n" +
                "        \"feedRollingPressureAct\":0,\n" +
                "        \"rollingPressure1\":77,\n" +
                "        \"rollingPressureAct1\":77,\n" +
                "        \"rollingPressure2\":77,\n" +
                "        \"rollingPressureAct2\":77,\n" +
                "        \"rollingPressure3\":77,\n" +
                "        \"rollingPressureAct3\":77,\n" +
                "        \"rollingPressure4\":77,\n" +
                "        \"rollingPressureAct4\":77,\n" +
                "        \"outRollingPressure\":0,\n" +
                "        \"outRollingPressureAct\":0,\n" +
                "        \"ph1\":0,\n" +
                "        \"phAct1\":0,\n" +
                "        \"ph2\":0,\n" +
                "        \"phAct2\":0,\n" +
                "        \"waterRatio1\":88,\n" +
                "        \"waterRatioAct1\":88,\n" +
                "        \"waterRatio2\":88,\n" +
                "        \"waterRatioAct2\":88,\n" +
                "        \"waterRatio3\":88,\n" +
                "        \"waterRatioAct3\":88,\n" +
                "        \"waterRatio4\":88,\n" +
                "        \"waterRatioAct4\":88,\n" +
                "        \"gramWeight\":0,\n" +
                "        \"deviceType\":\"wash\",\n" +
                "        \"device\":\"1211-zw\"\n" +
                "    }\n" +
                "]";
        return JSON.parseArray(s, IotInfoDo.class);
    }
}
