
spring:
  application:
    # 应用名称
    name: netty
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-wait: 5000
        max-idle: 5
        min-idle: 1
    timeout: 5000
    # redisson
#    jedis:
#      pool:
#        max-active: 500
#        max-idle: 1000
#        max-wait: 6000
#        min-idle: 4
#    connect-timeout: 3000
  redis2:
    # Redis服务器地址
    host: 8.130.80.181
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器连接端口
    port: 6379
#    password: '123456'
    #连接超时时间（毫秒）
    timeout: 3600
    # 连接池最大连接数(使用负值表示没有限制) 默认为8
    lettuce.pool.max-active: 16
    # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
    lettuce.pool.max-wait: -1
    # 连接池中的最大空闲连接 默认为8
    lettuce.pool.max-idle: 8
    # 连接池中的最小空闲连接 默认为 0
    lettuce.pool.min-idle: 1

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
#    serialization:
#      write-dates-as-timestamps: true

  datasource:
    druid:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
      filters: stat
      initialSize: 100
      maxActive: 1000
      maxOpenPreparedStatements: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 500
      poolPreparedStatements: true
      stat-view-servlet:
        allow: 127.0.0.1,*
        enabled: true
        login-password: 123456
        login-username: admin
        reset-enable: false
        url-pattern: /druid/*
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      url: jdbc:mysql://localhost:3306/chat?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
      username: root
      password: password
      validationQuery: select 'x'
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  port: 18092
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# ws://192.168.0.112:18888/ws
netty:
  server:
    port: 18888


mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  type-handlers-package: com.zw.cloud.netty.config.db.typehandlers.ext




