
spring:
  application:
    # 应用名称
    name: netty
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-wait: 5000
        max-idle: 5
    timeout: 5000
    # redisson
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        max-wait: 6000
        min-idle: 4
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

server:
  port: 18092

netty:
  server:
    port: 18888


