
spring:
  application:
    name: influxdb

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  influx:
    url:
    user:
    password:
    database:
    retentionPolicy: au
server:
  port: 10010
